### ISSUE TITLE
Monitoring for the 1 bit leak

### ISSUE THREAD

**Issue by caraitto** [wanderview/bounce-tracking-mitigations#6]
[0] mentions that "Ultimately, though, it may be necessary to weigh the cost of this 1 bit information leak against the gains in mitigating bounce tracking."

I think this 1 bit refers to "For example, if tracker.example reports back its oldest existing state to site1.example, then site1.example could infer that tracker.example has had an interaction. If it does not report any long-lived state, however, then site1.example could infer that the state was wiped." -- that is whether or not a site had an interaction or not.

However, IIUC, the site doesn't actually control whether or not an interaction occurs -- the user does? Is there a scenario where the site could trigger and control the leak repeatedly to transfer more than 1 bit across sites?

"An attacker could use existing XS leaks to determine if any logged-in state is present on a target site and then look to see if that state disappears after triggering the bounce." hints at the possibility of such a controlled leak, but I'm not entirely following? How would a site have logged in state and have its state cleared? Wouldn't this imply that there was no user interaction with that site? But then, how would the user be in a logged-in state on that site? 

I'd like to understand the above scenario a bit better.

In any event -- if there is still potential to use bounce tracking mitigation to leak information across sites (even if more limited than the original bounce tracking), would it be possible to monitor this for signs of tracking abuse?

[0] https://github.com/wanderview/bounce-tracking-mitigations/blob/main/explainer.md#privacy-and-security-considerations:~:text=Ultimately%2C%20though%2C%20it%20may%20be%20necessary%20to%20weigh%20the%20cost%20of%20this%201%20bit%20information%20leak%20against%20the%20gains%20in%20mitigating%20bounce%20tracking.

**Comment by caraitto** [comment]
@wanderview Hi, friendly ping?

**Comment by BrianLefler** [comment]
I believe your understanding is correct and we haven't come up with any plausible scenarios to repeatedly transmit bits from a single redirector—at least, when interactions are used as the signal for supported use cases and interactions are stored for a long period.

An attacker with a social engineering scheme that can reliably induce user interactions on arbitrary sites could transfer N bits by using N distinct sites.  That said, such an attacker can use that same capability to evade the mitigation entirely—get a single domain classified as a valid use case, and have that site transmit a single identifier navigationally.

Evasion is a known risk, but the tracker is at least paying the cost of having to induce an interaction and be visible in the url bar.  Worth noting Apple supplemented their bounce tracking mitigation with a secondary intervention targeting evasion, ['SameSite=Strict Cookie Jail for Bounce Trackers'](https://webkit.org/blog/11338/cname-cloaking-and-bounce-tracking-defense/).

**Comment by caraitto** [comment]
@wanderview Thanks for the response -- do you think there are any metrics we could use to monitor for abuse?

**Comment by wanderview** [comment]
Thanks for responding Brian.  I've been traveling recently and just catching up on mail/issues.

> do you think there are any metrics we could use to monitor for abuse?

Who is "we" in this question?  Browsers?  Site operators?  Someone else?

I think any metrics around this would be similar to trying to measure XS leaks since its a dependency for this attack.  I'm not super familiar with that space, but my impression is that those cannot be automatically measured.  (I assume if we could deterministically identify and measure them we would instead be doing something to block the leaks.)

**Comment by caraitto** [comment]
Whoops, sorry for mixing up Brian and Ben :/

> Who is "we" in this question? Browsers? Site operators? Someone else?
Browsers (or maybe crawlers with headless browsers?) -- for instance, the proportion of bounces that are have state wiped vs not (state wiped 0% of the time or 100% of the time leaks less information compared to state wiped 50% of the time). Maybe there's other useful metrics?

In general, when there's potential for abuse that's difficult to mitigate, it might be good to monitor to determine if abuse is actually happening.

However, IIUC it sounds like this attack requires other cross-site leaks, so maybe it's not so useful as a cross site leak vector on its own?

**Comment by wanderview** [comment]
> However, IIUC it sounds like this attack requires other cross-site leaks, so maybe it's not so useful as a cross site leak vector on its own?

Correct, an attacker would need to identify a vulnerable site with both 1) a redirect flow that can be triggered by the attacker and 2) a cross-site leak exposing whether state is stored on the site or not.  This would seem to rapidly reduce the utility of trying to extract N bits.

Also, consider that the attacker has to wait for the deletion to occur.  For some browsers today deletion is delayed by many hours, so it would be time consuming for an attacker to achieve.  We will likely also fuzz the timing of when we actually perform the deletion in order to make the attack more costly to perform.

**Comment by caraitto** [comment]
> Correct, an attacker would need to identify a vulnerable site

Just to clarify -- are there any concerns if the "vulnerable site" is actively colluding / collaborating with the attacker? (That is generally the threat model we're using for identifiability concerns -- that is, can identity be transmitted between cooperating sites?).

Otherwise, it does seem like this is a difficult attack to pull off. If there are any browser metrics to monitor for abuse, we should consider adding them. Otherwise, this bounce tracking mitigation proposal SGTM.

**Comment by wanderview** [comment]
> Just to clarify -- are there any concerns if the "vulnerable site" is actively colluding / collaborating with the attacker? (That is generally the threat model we're using for identifiability concerns -- that is, can identity be transmitted between cooperating sites?).

It does not seem someone would need an attack in that scenario.  If the sites are collaborating and the bouncer has an interaction then it can do all the things available today.

**Comment by caraitto** [comment]
Got it, so IIUC, assuming all cross-site leaks are fixed (including bounce tracking, link decoration, storage partitioning, fingerprinting, etc), there shouldn't be an additional cross site tracking capability introduced by this proposal, IIUC?

If so, we can go ahead and close this issue.
